language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gfortran subversion git swig
  # gcc-5 g++-5 gfortran-5
  #- git clone https://github.com/bumps/bumps.git
  #- pip install ./bumps
  - pip install bumps
  - pip install nose numpy scipy matplotlib
install:
  #- alias gcc="gcc-5"
  #- alias g++="g++-5"
  #- alias gfortran="gfortran-5"
  - which python3-config
  - which python-config
  - "./build.sh"
# command to run tests
script:
  - cd hklgen
  - PYTHONPATH=. nosetests
