language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gfortran python3 python3-dev python3-numpy python3-scipy python3-matplotlib python3-pip subversion git swig
  # gcc-5 g++-5 gfortran-5
  - git clone https://github.com/bumps/bumps.git
  - sudo pip3 install ./bumps
  - sudo pip3 install nose
install:
  #- alias gcc="gcc-5"
  #- alias g++="g++-5"
  #- alias gfortran="gfortran-5"
  - "./build.sh"
# command to run tests
script:
  - cd hklgen
  - PYTHONPATH=. nosetests
